<?php
class Product {
    public static $categories = ['Clothing'=> ['Men' => ['Suits' => 'Костюмы',
                                                        'Shoes' => 'Обувь',
                                                        'Jeans' => 'Джинсы',
                                                        'Sunglasses' => 'Очки',
                                                        'Sport Wear' => 'Спортивная одежда',
                                                        'Underwear' => 'Нижнее белье',
                                                        'Shirts' => 'Футболки'],
                                              'Women' => ['Handbags' => 'Сумки',
                                                        'Jewelry' => 'Ювелирные украшения',
                                                        'Swimwear' => 'Купальные костюмы',
                                                        'Underwear' => 'Нижнее белье',
                                                        'Skirts' => 'Юбки',
                                                        'Shoes' => 'Обувь',
                                                        'Winter wear' => 'Зимняя одежда'],
                                              'Boys' => ['Toys & Games' => 'Игрушки и игры',
                                                        'Jeans' => 'Джинсы',
                                                        'Shirts' => 'Футболки',
                                                        'Shoes' => 'Обувь',
                                                        'Shool bags' => 'Школьные сумки',
                                                        'Suits' => 'Костюмы',
                                                        'Winter wear' => 'Зимняя одежда'],
    ],
        'Electronics' => 'Электроника',
        'Shoes'=>'Обувь',
        'Watches' => 'Часы',
        'Jewellery' => 'Ювелирные изделия',
        'Health and Beauty' => 'Здоровье и красота',
        'Kids and Babies' => 'Дети и младенцы',
        'Sports' => 'Спорт',
        'Home and Garden' => 'Дом и сад'
        ]
}